### ISSUE TITLE
Missing SQL Database

### ISSUE THREAD

**Issue by Hajj53** [Ahsan804/ASP-.Net-School-Management-System#1]
Hi, am impressed with the web app... I want to continue building on it but its missing the SQL Database, are you able to provide me with the SQL Database?

<img width="960" alt="noSQL" src="https://github.com/DevAhsaNOp/ASP.Net-School-Management-System/assets/55025756/0b86ff4e-6a64-4bcc-8018-3985014bda8f">

**Comment by DevAhsaNOp** [comment]
Hi @Hajj53 ,

Thank you for your kind comments. I apologize for the issue you're facing in finding the database. You can use the following link as a reference for the **MySQL Database** :  [MySQL Database](https://github.com/DevAhsaNOp/ASP.Net-School-Management-System/blob/dd92c3eb0f884c836ab2877855d60d1cc96e3461/Documents/lms.sql)

**Comment by Hajj53** [comment]
You are welcome and thank you.
    On Tuesday, January 9, 2024 at 08:02:32 PM GMT+2, Muhammad Ahsan ***@***.***> wrote:  
 
 


Hi @Hajj53 ,

Thank you for your kind comments. I apologize for the issue you're facing in finding the database. You can use the following link as a reference for the MySQL Database : MySQL Database
